export const RISK_DIALOGUE = {
  lateTime: [
    "You usually have this done by now. What's the hold up?",
    "Clock's ticking. Don't break your rhythm today.",
    "You're officially off schedule. Let's get this crossed off.",
    "Hey, just a heads up that you're running late on this one.",
    "Checking the stats and you're cutting it close. Get on it.",
    "You usually knock this out hours ago. Everything okay? Let's do this.",
    "It's getting late for this habit. Don't push it to the last minute.",
    "I know you're tired, but you're way past your usual time for this.",
    "Let's not make a habit of being this late. Get it done.",
    "You're in the red zone for time. Time to execute.",
    "Just a gentle nudge: you're behind your usual pace.",
    "Don't let the day slip away without hitting this.",
    "You're stretching the deadline today. Lock in.",
    "I see you putting this off. Let's get it out of the way.",
    "Midnight is creeping up faster than you think.",
    "You're usually so consistent with the timing on this. What happened today?",
    "Let's get this done so you can actually relax tonight.",
    "You're playing a dangerous game with the clock right now.",
    "Hey, you're out of your usual timezone for this task. Wrap it up.",
    "Don't wait until you're too exhausted. Do it now.",
    "Statistically, you're running way behind. Prove the math wrong.",
    "I know it's late, but a strike is worse. Get it done.",
    "You're drifting off your baseline. Pull it back.",
    "This is usually done by now. Don't let it slide.",
    "Let's close this loop before it gets any later.",
    "You're testing the limits of the day. Time to focus.",
    "I'm keeping an eye on the time, and you should too. Let's go.",
    "Just do it now so you don't have to stress about it in bed.",
    "You're way off your average completion time. Catch up.",
    "Don't let tomorrow's problems start tonight. Finish this.",
    "The later it gets, the harder it is. Just start.",
    "You've been procrastinating this one, haven't you? Time's up.",
    "Let's not trigger a strike over poor timing. Get it done.",
    "You're leaving this dangerously late.",
    "Hey, wrap this up. You're behind schedule.",
    "Don't ruin a good streak just because you lost track of time.",
    "The day is almost over. Don't leave this hanging.",
    "You're past your usual window. Squeeze it in now.",
    "I'm flagging this because you're usually done by now. Check it off.",
    "Stop scrolling and knock this out. It's getting late.",
    "You're running out of runway for today.",
    "Let's secure this win before it gets any darker out.",
    "You're statistically late. Let's fix that.",
    "Don't let a late start turn into a missed day.",
    "Hey, I see you. It's late, but you still have time.",
    "Wrap this up so I can stop nagging you about the time.",
    "You're off your rhythm today. Get this done and reset.",
    "Don't force me to hand out a strike because you waited too long.",
    "It's getting down to the wire. Execute.",
    "You usually have this cleared by now. Finish strong."
  ],

  highLoad: [
    "You've got a lot left on the board today. Start chipping away.",
    "The list is looking a bit heavy. Pick one and go.",
    "You're piling up tasks. Let's knock this one out to lighten the load.",
    "Hey, you have more active habits left than usual. Time to focus.",
    "Don't let the list overwhelm you. Just do this one right now.",
    "You've got a backlog building up today. Start here.",
    "Things are piling up. Let's get some momentum going.",
    "I see a lot of unchecked boxes. Let's fix this one first.",
    "You're carrying too much load for this time of day. Execute.",
    "Let's thin out this list before it becomes a problem.",
    "You have a lot on your plate today. Don't fall behind.",
    "The math says you have too many tasks left. Knock this one out.",
    "You're risking a multi-strike if you don't start clearing these.",
    "Take a breath, look at the list, and just finish this one.",
    "You're tracking way behind on your overall load. Time to work.",
    "Don't let the pile get any bigger. Check this off.",
    "You've got a busy dashboard today. Let's clear some space.",
    "Hey, the workload is high today. You need to start moving.",
    "One at a time. Start with this one.",
    "You're dangerously overloaded right now. Execute this task.",
    "Let's shrink that active list, starting right now.",
    "You have more left to do than your average. Pick up the pace.",
    "The tasks are adding up. Don't get buried.",
    "You need a win right now to get the momentum going. Do this.",
    "Let's lighten the mental load. Check this one off the list.",
    "You're juggling too much today. Drop this one into the 'done' pile.",
    "Clear this out so you can focus on the rest of the list.",
    "Hey, your active load is spiking. Let's handle this.",
    "You can't do them all at once, but you can do this one right now.",
    "The dashboard is looking a little too crowded. Let's clean it up.",
    "You're statistically overloaded. Time to grind.",
    "Don't let the list intimidate you. Just start.",
    "You've got a lot of open loops today. Close this one.",
    "Let's get your task count back down to normal.",
    "You're behind on your volume today. Let's catch up.",
    "Too many things left to do. Make this one disappear.",
    "You're carrying a heavy load into the evening. Get moving.",
    "Let's check this off so you have one less thing to worry about.",
    "You're stacking tasks. Unstack this one.",
    "The math is worried about your workload. Prove it wrong.",
    "You have a lot of targets left today. Hit this one.",
    "Let's trim down that active list. Go.",
    "You're looking at a heavy backlog. Start chipping.",
    "Don't let the volume slow you down. Execute.",
    "Hey, you've got a lot to do. Less thinking, more doing.",
    "Let's get this one out of the way to free up some bandwidth.",
    "You're running hot on active tasks. Cool it down by finishing this.",
    "The list is long today. Shorten it.",
    "You're carrying too much right now. Knock this out.",
    "Start checking these off before the strikes start rolling in."
  ],

  generalRisk: [
    "I'm seeing a high chance of a strike here. Prove the math wrong.",
    "Don't let this slide into tomorrow.",
    "Hey, this one is looking risky. Let's get it done.",
    "I know you can do this, but the data says you might slip. Lock in.",
    "You're flirting with a strike right now. Wrap it up.",
    "Let's secure this habit before it becomes a problem.",
    "You're in the danger zone for this task. Time to execute.",
    "I'm flagging this as high risk. Don't let me down.",
    "Let's not take a strike today. Check this off.",
    "You're cutting it dangerously close. Get moving.",
    "Hey, don't drop the ball on this one today.",
    "The algorithm is doubting you. Show it who's boss.",
    "You're trending toward a miss. Let's pull it back.",
    "I see a strike in your future if you don't act now.",
    "Let's keep the streak alive. Do the work.",
    "You're teetering on the edge with this habit. Finish it.",
    "Don't make me pull out the Lockout Overlay. Get this done.",
    "You're highly likely to miss this today. Let's change that.",
    "Hey, focus up. This one is slipping away.",
    "Let's get this crossed off the board, safely.",
    "You're in the red. Time to step up and clear this.",
    "Don't let a moment of laziness turn into a permanent strike.",
    "I'm warning you early so you have time to fix it. Go.",
    "You're statistically at risk here. Prove me wrong.",
    "Let's put this one to bed before it becomes an issue.",
    "You're making me nervous with this one. Check it off.",
    "Don't gamble with your strikes. Just do the habit.",
    "Hey, I've got a bad feeling about this one. Let's finish it.",
    "You're on thin ice with this task today. Execute.",
    "Let's not ruin a good day with a silly strike. Get it done.",
    "The risk score is spiking. Handle this now.",
    "I'm throwing a flag on this play. Get moving.",
    "You're dangerously close to failing this today. Lock in.",
    "Don't let this be the one that gets away.",
    "Hey, you're at risk here. Let's get back on track.",
    "Let's clear this out of the danger zone.",
    "You're looking at a highly probable strike. Change the outcome.",
    "Don't sleep on this habit today. Get it done.",
    "I'm stepping in because you're about to slip. Finish it.",
    "You're walking right into a strike. Pivot and execute.",
    "Let's keep the dashboard clean. Knock this out.",
    "You're at high risk for a miss. Don't let it happen.",
    "Hey, I need you to focus on this for a minute and just do it.",
    "You're dangerously close to the edge. Pull back and finish.",
    "Let's not make things harder than they need to be. Do the habit.",
    "The math says you're going to fail. I know you won't. Go.",
    "You're staring down a strike. Let's clear it.",
    "Don't let your guard down. This one needs doing.",
    "Hey, this is your official warning. Get it done.",
    "I'm not letting you slip on my watch. Execute this habit."
  ]
};

/**
 * Pulls a completely random, casual warning string based on the risk scenario.
 */
export function getRandomNudge(scenario: keyof typeof RISK_DIALOGUE, habitTitle: string): string {
  const lines = RISK_DIALOGUE[scenario];
  const randomLine = lines[Math.floor(Math.random() * lines.length)];
  
  return `${randomLine} [${habitTitle}]`;
}
