import { 
  // Productivity
  Target, CheckCircle2, List, Clipboard, CalendarDays, Clock, Rocket, Flag, Zap, Award, 
  Briefcase, Layout, Archive, Bookmark, Pen, Edit3, Layers, Inbox, Mail, Send, 
  Bell, Filter, Search, Shield, Lock, Unlock, Key, Settings, Sliders, Trash, 
  ExternalLink, Link, Share2, Download, Upload, Copy, Save, Plus, Minus, X, 
  Menu, MoreHorizontal, GripVertical, RefreshCw, Repeat, Play, Pause, Timer, 
  History, Activity, Gauge,
  // Health & Fitness
  Dumbbell, Heart, BicepsFlexed, Footprints, Apple, Salad, Utensils, GlassWater, 
  Bed, Bath, Baby, Bike, Bone, Brain, Pill, Stethoscope, Syringe, Thermometer, 
  Weight, Flame, Wind, Smile, Frown, Meh, Cigarette, CigaretteOff, Flower, 
  Mountain, TreePine, Cat, Dog, Tent, Umbrella, HeartPulse, BrainCircuit,
  Banana, Carrot, Cherry, Citrus, Egg, Fish, Milk, Soup, MountainSnow, 
  Radiation, Skull, TentTree, TreeDeciduous, UserRoundCheck,
  // Tech & Dev
  Cpu, Laptop, Monitor, Smartphone, Tablet, Watch, Terminal, Code, Code2, 
  Database, Server, HardDrive, Mouse, Keyboard, Speaker, Headphones, Mic, 
  Camera, Video, Wifi, Bluetooth, Cast, Battery, BatteryCharging, Cloud, 
  Command, Eye, Fingerprint, Scan, Power, Network, GitBranch, GitCommit, 
  GitMerge, GitPullRequest, Accessibility, Airplay, Binary, Bot, Cable, 
  CircuitBoard, CloudCog, Codesandbox, Codepen, Figma, Github, Gitlab, 
  Webhook, AppWindow, Atom,
  // Finance
  Banknote, Coins, CreditCard, DollarSign, Euro, IndianRupee, PoundSterling, 
  JapaneseYen, Landmark, PiggyBank, Receipt, ShoppingCart, ShoppingBag, Wallet, 
  TrendingUp, TrendingDown, Percent, Calculator, PieChart, BarChart3, Gift, 
  Tag, Ticket, Bitcoin, Gem, HandCoins, ReceiptJapaneseYen, Scale, ShieldCheck, 
  ShoppingBasket, Store, Vault, CircleDollarSign, Landmark as Bank, 
  Briefcase as BriefcaseMoney, LineChart,
  // Home & Life
  Home, Building2, Car, Plane, TrainFront, Bus, Map, MapPin, Navigation, 
  Coffee, Pizza, Beer, Wine, Cake, Candy, Cookie, Music, Gamepad2, Tv, 
  Brush, Hammer, Wrench, Shirt, Glasses, Sun, Moon, CloudRain, CloudSnow, 
  CloudLightning, Sunrise, Sunset, Armchair, Binoculars, Bird, Bomb, BookHeart, 
  ChefHat, Construction, DoorOpen, Eraser, Hotel, Luggage, Microwave, 
  PartyPopper, PawPrint, Refrigerator, Sofa, Tractor, Waves,
  // Mindfulness
  Sparkles, Ear, Vibrate, CloudSun, Dna, Rainbow, 
  BrainCircuit as MindCircuit, HeartPulse as Vitality, Sun as VitalEnergy, 
  Mountain as Peace, Trees as Forest, Waves as Flow, Leaf as Organic, 
  Feather as Soft, Infinity as Endless, Anchor as Grounded, 
  Compass as Guide, MoonStar as Dream, 
  Flower2 as Bloom, Flower as Zen
} from "lucide-react";

export type IconCategory = 
  | "PRODUCTIVITY"
  | "HEALTH & FITNESS"
  | "TECH & DEV"
  | "FINANCE"
  | "HOME & LIFE"
  | "MINDFULNESS";

export interface IconItem {
  id: string;
  icon: any; // LucideIcon component
  category: IconCategory;
  tags: string[];
}

export const ICON_DATA: IconItem[] = [
  // [ PRODUCTIVITY ]
  { id: "Target", icon: Target, category: "PRODUCTIVITY", tags: ["goal", "focus", "aim", "objective"] },
  { id: "Check", icon: CheckCircle2, category: "PRODUCTIVITY", tags: ["done", "completed", "finish", "task"] },
  { id: "List", icon: List, category: "PRODUCTIVITY", tags: ["todo", "tasks", "items", "ordered"] },
  { id: "Clipboard", icon: Clipboard, category: "PRODUCTIVITY", tags: ["notes", "copy", "tasks", "document"] },
  { id: "Calendar", icon: CalendarDays, category: "PRODUCTIVITY", tags: ["date", "schedule", "time", "event"] },
  { id: "Clock", icon: Clock, category: "PRODUCTIVITY", tags: ["time", "timer", "duration", "watch"] },
  { id: "Rocket", icon: Rocket, category: "PRODUCTIVITY", tags: ["launch", "start", "fast", "growth"] },
  { id: "Flag", icon: Flag, category: "PRODUCTIVITY", tags: ["priority", "marker", "finish", "milestone"] },
  { id: "Zap", icon: Zap, category: "PRODUCTIVITY", tags: ["energy", "quick", "power", "bolt"] },
  { id: "Award", icon: Award, category: "PRODUCTIVITY", tags: ["prize", "medal", "achievement", "success"] },
  { id: "Briefcase", icon: Briefcase, category: "PRODUCTIVITY", tags: ["work", "job", "business", "office"] },
  { id: "Layout", icon: Layout, category: "PRODUCTIVITY", tags: ["design", "structure", "template", "grid"] },
  { id: "Archive", icon: Archive, category: "PRODUCTIVITY", tags: ["store", "box", "save", "history"] },
  { id: "Bookmark", icon: Bookmark, category: "PRODUCTIVITY", tags: ["save", "favorite", "marker", "read"] },
  { id: "Pen", icon: Pen, category: "PRODUCTIVITY", tags: ["write", "edit", "draw", "input"] },
  { id: "Edit", icon: Edit3, category: "PRODUCTIVITY", tags: ["modify", "write", "change", "update"] },
  { id: "Layers", icon: Layers, category: "PRODUCTIVITY", tags: ["stack", "overlap", "structure", "depth"] },
  { id: "Inbox", icon: Inbox, category: "PRODUCTIVITY", tags: ["mail", "receive", "incoming", "box"] },
  { id: "Mail", icon: Mail, category: "PRODUCTIVITY", tags: ["email", "message", "letter", "contact"] },
  { id: "Send", icon: Send, category: "PRODUCTIVITY", tags: ["submit", "outgoing", "message", "paperplane"] },
  { id: "Bell", icon: Bell, category: "PRODUCTIVITY", tags: ["alert", "reminder", "alarm", "sound"] },
  { id: "Filter", icon: Filter, category: "PRODUCTIVITY", tags: ["refine", "sort", "funnel", "select"] },
  { id: "Search", icon: Search, category: "PRODUCTIVITY", tags: ["find", "look", "magnifying", "query"] },
  { id: "Shield", icon: Shield, category: "PRODUCTIVITY", tags: ["security", "protect", "safe", "guard"] },
  { id: "Lock", icon: Lock, category: "PRODUCTIVITY", tags: ["secure", "closed", "private", "safety"] },
  { id: "Unlock", icon: Unlock, category: "PRODUCTIVITY", tags: ["open", "accessible", "free", "security"] },
  { id: "Key", icon: Key, category: "PRODUCTIVITY", tags: ["access", "password", "security", "unlock"] },
  { id: "Settings", icon: Settings, category: "PRODUCTIVITY", tags: ["config", "gear", "options", "tools"] },
  { id: "Sliders", icon: Sliders, category: "PRODUCTIVITY", tags: ["controls", "adjust", "preferences", "levels"] },
  { id: "Trash", icon: Trash, category: "PRODUCTIVITY", tags: ["delete", "remove", "bin", "discard"] },
  { id: "ExternalLink", icon: ExternalLink, category: "PRODUCTIVITY", tags: ["open", "out", "link", "new"] },
  { id: "Link", icon: Link, category: "PRODUCTIVITY", tags: ["connect", "url", "chain", "attachment"] },
  { id: "Share", icon: Share2, category: "PRODUCTIVITY", tags: ["social", "connect", "network", "distribute"] },
  { id: "Download", icon: Download, category: "PRODUCTIVITY", tags: ["save", "import", "down", "receive"] },
  { id: "Upload", icon: Upload, category: "PRODUCTIVITY", tags: ["send", "export", "up", "transmit"] },
  { id: "Copy", icon: Copy, category: "PRODUCTIVITY", tags: ["duplicate", "clone", "clipboard", "repeat"] },
  { id: "Save", icon: Save, category: "PRODUCTIVITY", tags: ["store", "disk", "keep", "preserve"] },
  { id: "Plus", icon: Plus, category: "PRODUCTIVITY", tags: ["add", "new", "create", "increase"] },
  { id: "Minus", icon: Minus, category: "PRODUCTIVITY", tags: ["remove", "decrease", "less", "subtract"] },
  { id: "X", icon: X, category: "PRODUCTIVITY", tags: ["close", "cancel", "remove", "stop"] },
  { id: "Menu", icon: Menu, category: "PRODUCTIVITY", tags: ["navigation", "hamburger", "list", "options"] },
  { id: "More", icon: MoreHorizontal, category: "PRODUCTIVITY", tags: ["dots", "options", "menu", "ellipsis"] },
  { id: "Grip", icon: GripVertical, category: "PRODUCTIVITY", tags: ["drag", "handle", "move", "reorder"] },
  { id: "Refresh", icon: RefreshCw, category: "PRODUCTIVITY", tags: ["reload", "sync", "update", "cycle"] },
  { id: "Repeat", icon: Repeat, category: "PRODUCTIVITY", tags: ["loop", "cycle", "again", "recurring"] },
  { id: "Play", icon: Play, category: "PRODUCTIVITY", tags: ["start", "run", "media", "begin"] },
  { id: "Pause", icon: Pause, category: "PRODUCTIVITY", tags: ["stop", "wait", "media", "break"] },
  { id: "Timer", icon: Timer, category: "PRODUCTIVITY", tags: ["countdown", "limit", "duration", "time"] },
  { id: "History", icon: History, category: "PRODUCTIVITY", tags: ["past", "recent", "time", "back"] },
  { id: "Activity", icon: Activity, category: "PRODUCTIVITY", tags: ["pulse", "heartrate", "monitoring", "active"] },
  { id: "Gauge", icon: Gauge, category: "PRODUCTIVITY", tags: ["meter", "speed", "performance", "level"] },

  // [ HEALTH & FITNESS ]
  { id: "Dumbbell", icon: Dumbbell, category: "HEALTH & FITNESS", tags: ["gym", "workout", "weights", "exercise"] },
  { id: "Heart", icon: Heart, category: "HEALTH & FITNESS", tags: ["love", "health", "cardio", "life"] },
  { id: "Biceps", icon: BicepsFlexed, category: "HEALTH & FITNESS", tags: ["strength", "muscle", "power", "bodybuilding"] },
  { id: "Footprints", icon: Footprints, category: "HEALTH & FITNESS", tags: ["walk", "steps", "track", "movement"] },
  { id: "Apple", icon: Apple, category: "HEALTH & FITNESS", tags: ["food", "fruit", "healthy", "diet"] },
  { id: "Salad", icon: Salad, category: "HEALTH & FITNESS", tags: ["food", "healthy", "diet", "nutrition"] },
  { id: "Utensils", icon: Utensils, category: "HEALTH & FITNESS", tags: ["eat", "meal", "food", "dinner"] },
  { id: "GlassWater", icon: GlassWater, category: "HEALTH & FITNESS", tags: ["drink", "hydrate", "liquid", "health"] },
  { id: "Bed", icon: Bed, category: "HEALTH & FITNESS", tags: ["sleep", "rest", "night", "recovery"] },
  { id: "Bath", icon: Bath, category: "HEALTH & FITNESS", tags: ["clean", "shower", "relax", "hygiene"] },
  { id: "Baby", icon: Baby, category: "HEALTH & FITNESS", tags: ["child", "family", "parenting", "newborn"] },
  { id: "Bike", icon: Bike, category: "HEALTH & FITNESS", tags: ["cycle", "exercise", "transport", "outdoor"] },
  { id: "Bone", icon: Bone, category: "HEALTH & FITNESS", tags: ["anatomy", "calcium", "strength", "pet"] },
  { id: "Brain", icon: Brain, category: "HEALTH & FITNESS", tags: ["mind", "mental", "intelligence", "thought"] },
  { id: "Pill", icon: Pill, category: "HEALTH & FITNESS", tags: ["medicine", "drugs", "health", "pharmacy"] },
  { id: "Stethoscope", icon: Stethoscope, category: "HEALTH & FITNESS", tags: ["doctor", "medical", "checkup", "hospital"] },
  { id: "Syringe", icon: Syringe, category: "HEALTH & FITNESS", tags: ["vaccine", "medical", "injection", "blood"] },
  { id: "Thermometer", icon: Thermometer, category: "HEALTH & FITNESS", tags: ["fever", "heat", "temperature", "medical"] },
  { id: "Weight", icon: Weight, category: "HEALTH & FITNESS", tags: ["scale", "body", "mass", "diet"] },
  { id: "Flame", icon: Flame, category: "HEALTH & FITNESS", tags: ["calories", "burn", "fire", "energy"] },
  { id: "Wind", icon: Wind, category: "HEALTH & FITNESS", tags: ["breath", "air", "motion", "weather"] },
  { id: "Smile", icon: Smile, category: "HEALTH & FITNESS", tags: ["happy", "mental", "mood", "face"] },
  { id: "Frown", icon: Frown, category: "HEALTH & FITNESS", tags: ["sad", "mental", "mood", "face"] },
  { id: "Meh", icon: Meh, category: "HEALTH & FITNESS", tags: ["neutral", "mental", "mood", "face"] },
  { id: "Smoking", icon: Cigarette, category: "HEALTH & FITNESS", tags: ["habit", "smoke", "tobacco", "unhealthy"] },
  { id: "NoSmoking", icon: CigaretteOff, category: "HEALTH & FITNESS", tags: ["quit", "stop", "smoke", "healthy"] },
  { id: "Flower", icon: Flower, category: "HEALTH & FITNESS", tags: ["yoga", "relax", "mindful", "calm"] },
  { id: "Mountain", icon: Mountain, category: "HEALTH & FITNESS", tags: ["climb", "hike", "nature", "outdoor"] },
  { id: "Tree", icon: TreePine, category: "HEALTH & FITNESS", tags: ["nature", "forest", "outdoor", "park"] },
  { id: "Dog", icon: Dog, category: "HEALTH & FITNESS", tags: ["pet", "animal", "walk", "companion"] },
  { id: "Cat", icon: Cat, category: "HEALTH & FITNESS", tags: ["pet", "animal", "companion", "home"] },
  { id: "Tent", icon: Tent, category: "HEALTH & FITNESS", tags: ["camp", "outdoor", "travel", "nature"] },
  { id: "Umbrella", icon: Umbrella, category: "HEALTH & FITNESS", tags: ["rain", "protect", "weather", "sun"] },
  { id: "HeartPulse", icon: HeartPulse, category: "HEALTH & FITNESS", tags: ["medical", "health", "cardio", "life"] },
  { id: "BrainCircuit", icon: BrainCircuit, category: "HEALTH & FITNESS", tags: ["mind", "mental", "smart", "ai"] },
  { id: "Banana", icon: Banana, category: "HEALTH & FITNESS", tags: ["fruit", "food", "healthy", "potassium"] },
  { id: "Carrot", icon: Carrot, category: "HEALTH & FITNESS", tags: ["food", "veggie", "healthy", "diet"] },
  { id: "Cherry", icon: Cherry, category: "HEALTH & FITNESS", tags: ["fruit", "food", "sweet", "healthy"] },
  { id: "Citrus", icon: Citrus, category: "HEALTH & FITNESS", tags: ["fruit", "food", "healthy", "lemon"] },
  { id: "Egg", icon: Egg, category: "HEALTH & FITNESS", tags: ["food", "protein", "breakfast", "cooking"] },
  { id: "Fish", icon: Fish, category: "HEALTH & FITNESS", tags: ["food", "healthy", "animal", "ocean"] },
  { id: "Milk", icon: Milk, category: "HEALTH & FITNESS", tags: ["drink", "dairy", "healthy", "calcium"] },
  { id: "Soup", icon: Soup, category: "HEALTH & FITNESS", tags: ["food", "meal", "hot", "healthy"] },
  { id: "MountainSnow", icon: MountainSnow, category: "HEALTH & FITNESS", tags: ["nature", "climb", "cold", "winter"] },
  { id: "Radiation", icon: Radiation, category: "HEALTH & FITNESS", tags: ["danger", "hazard", "medical", "energy"] },
  { id: "Skull", icon: Skull, category: "HEALTH & FITNESS", tags: ["danger", "death", "hazard", "toxic"] },
  { id: "TentTree", icon: TentTree, category: "HEALTH & FITNESS", tags: ["camp", "outdoor", "nature", "travel"] },
  { id: "TreeDeciduous", icon: TreeDeciduous, category: "HEALTH & FITNESS", tags: ["nature", "park", "outdoor", "green"] },
  { id: "UserCheck", icon: UserRoundCheck, category: "HEALTH & FITNESS", tags: ["verified", "person", "account", "safe"] },

  // [ TECH & DEV ]
  { id: "Cpu", icon: Cpu, category: "TECH & DEV", tags: ["chip", "processor", "hardware", "computer"] },
  { id: "Laptop", icon: Laptop, category: "TECH & DEV", tags: ["computer", "work", "device", "mobile"] },
  { id: "Monitor", icon: Monitor, category: "TECH & DEV", tags: ["screen", "display", "computer", "desktop"] },
  { id: "Smartphone", icon: Smartphone, category: "TECH & DEV", tags: ["phone", "mobile", "device", "call"] },
  { id: "Tablet", icon: Tablet, category: "TECH & DEV", tags: ["device", "screen", "mobile", "ipad"] },
  { id: "Watch", icon: Watch, category: "TECH & DEV", tags: ["wearable", "time", "clock", "device"] },
  { id: "Terminal", icon: Terminal, category: "TECH & DEV", tags: ["code", "command", "cli", "dev"] },
  { id: "Code", icon: Code, category: "TECH & DEV", tags: ["programming", "dev", "script", "brackets"] },
  { id: "Code2", icon: Code2, category: "TECH & DEV", tags: ["programming", "dev", "script", "tags"] },
  { id: "Database", icon: Database, category: "TECH & DEV", tags: ["storage", "data", "sql", "server"] },
  { id: "Server", icon: Server, category: "TECH & DEV", tags: ["cloud", "hosting", "network", "backend"] },
  { id: "HardDrive", icon: HardDrive, category: "TECH & DEV", tags: ["storage", "disk", "hardware", "memory"] },
  { id: "Mouse", icon: Mouse, category: "TECH & DEV", tags: ["input", "cursor", "hardware", "computer"] },
  { id: "Keyboard", icon: Keyboard, category: "TECH & DEV", tags: ["input", "typing", "hardware", "computer"] },
  { id: "Speaker", icon: Speaker, category: "TECH & DEV", tags: ["audio", "sound", "music", "hardware"] },
  { id: "Headphones", icon: Headphones, category: "TECH & DEV", tags: ["audio", "music", "listen", "private"] },
  { id: "Mic", icon: Mic, category: "TECH & DEV", tags: ["audio", "voice", "record", "input"] },
  { id: "Camera", icon: Camera, category: "TECH & DEV", tags: ["photo", "image", "capture", "video"] },
  { id: "Video", icon: Video, category: "TECH & DEV", tags: ["movie", "record", "camera", "motion"] },
  { id: "Wifi", icon: Wifi, category: "TECH & DEV", tags: ["network", "internet", "wireless", "connection"] },
  { id: "Bluetooth", icon: Bluetooth, category: "TECH & DEV", tags: ["wireless", "connection", "pair", "device"] },
  { id: "Cast", icon: Cast, category: "TECH & DEV", tags: ["stream", "display", "tv", "connect"] },
  { id: "Battery", icon: Battery, category: "TECH & DEV", tags: ["power", "energy", "level", "charge"] },
  { id: "BatteryCharging", icon: BatteryCharging, category: "TECH & DEV", tags: ["power", "charge", "energy", "plug"] },
  { id: "Cloud", icon: Cloud, category: "TECH & DEV", tags: ["network", "storage", "online", "sky"] },
  { id: "Command", icon: Command, category: "TECH & DEV", tags: ["keyboard", "mac", "shortcut", "apple"] },
  { id: "Eye", icon: Eye, category: "TECH & DEV", tags: ["view", "visible", "watch", "look"] },
  { id: "Fingerprint", icon: Fingerprint, category: "TECH & DEV", tags: ["security", "id", "auth", "biometric"] },
  { id: "Scan", icon: Scan, category: "TECH & DEV", tags: ["camera", "qr", "barcode", "detect"] },
  { id: "Power", icon: Power, category: "TECH & DEV", tags: ["off", "on", "start", "shutdown"] },
  { id: "Network", icon: Network, category: "TECH & DEV", tags: ["connect", "nodes", "structure", "internet"] },
  { id: "GitBranch", icon: GitBranch, category: "TECH & DEV", tags: ["process", "git", "branch", "path"] },
  { id: "GitCommit", icon: GitCommit, category: "TECH & DEV", tags: ["git", "save", "version", "dot"] },
  { id: "GitMerge", icon: GitMerge, category: "TECH & DEV", tags: ["git", "combine", "path", "version"] },
  { id: "GitPullRequest", icon: GitPullRequest, category: "TECH & DEV", tags: ["git", "review", "change", "contribution"] },
  { id: "Accessibility", icon: Accessibility, category: "TECH & DEV", tags: ["human", "design", "inclusive", "person"] },
  { id: "Airplay", icon: Airplay, category: "TECH & DEV", tags: ["stream", "display", "apple", "connect"] },
  { id: "Binary", icon: Binary, category: "TECH & DEV", tags: ["code", "math", "data", "computer"] },
  { id: "Bot", icon: Bot, category: "TECH & DEV", tags: ["ai", "robot", "automation", "chat"] },
  { id: "Cable", icon: Cable, category: "TECH & DEV", tags: ["connect", "hardware", "wire", "power"] },
  { id: "CircuitBoard", icon: CircuitBoard, category: "TECH & DEV", tags: ["hardware", "chip", "tech", "computer"] },
  { id: "CloudCog", icon: CloudCog, category: "TECH & DEV", tags: ["network", "settings", "automation", "online"] },
  { id: "Codesandbox", icon: Codesandbox, category: "TECH & DEV", tags: ["code", "dev", "project", "box"] },
  { id: "Codepen", icon: Codepen, category: "TECH & DEV", tags: ["code", "design", "social", "dev"] },
  { id: "Figma", icon: Figma, category: "TECH & DEV", tags: ["design", "tool", "creative", "ui"] },
  { id: "Github", icon: Github, category: "TECH & DEV", tags: ["code", "git", "social", "dev"] },
  { id: "Gitlab", icon: Gitlab, category: "TECH & DEV", tags: ["code", "git", "dev", "repo"] },
  { id: "Webhook", icon: Webhook, category: "TECH & DEV", tags: ["api", "connect", "internet", "dev"] },
  { id: "AppWindow", icon: AppWindow, category: "TECH & DEV", tags: ["software", "screen", "display", "interface"] },
  { id: "Atom", icon: Atom, category: "TECH & DEV", tags: ["science", "physics", "energy", "smart"] },

  // [ FINANCE ]
  { id: "Banknote", icon: Banknote, category: "FINANCE", tags: ["money", "cash", "bill", "currency"] },
  { id: "Coins", icon: Coins, category: "FINANCE", tags: ["money", "cash", "change", "currency"] },
  { id: "CreditCard", icon: CreditCard, category: "FINANCE", tags: ["payment", "bank", "card", "spending"] },
  { id: "Dollar", icon: DollarSign, category: "FINANCE", tags: ["money", "currency", "usd", "cash"] },
  { id: "Euro", icon: Euro, category: "FINANCE", tags: ["money", "currency", "eur", "cash"] },
  { id: "Rupee", icon: IndianRupee, category: "FINANCE", tags: ["money", "currency", "inr", "cash"] },
  { id: "Pound", icon: PoundSterling, category: "FINANCE", tags: ["money", "currency", "gbp", "cash"] },
  { id: "Yen", icon: JapaneseYen, category: "FINANCE", tags: ["money", "currency", "jpy", "cash"] },
  { id: "Landmark", icon: Landmark, category: "FINANCE", tags: ["bank", "building", "institution", "government"] },
  { id: "PiggyBank", icon: PiggyBank, category: "FINANCE", tags: ["savings", "money", "invest", "future"] },
  { id: "Receipt", icon: Receipt, category: "FINANCE", tags: ["bill", "payment", "invoice", "record"] },
  { id: "ShoppingCart", icon: ShoppingCart, category: "FINANCE", tags: ["buy", "ecommerce", "items", "shop"] },
  { id: "ShoppingBag", icon: ShoppingBag, category: "FINANCE", tags: ["buy", "ecommerce", "items", "shop"] },
  { id: "Wallet", icon: Wallet, category: "FINANCE", tags: ["money", "bank", "cash", "storage"] },
  { id: "TrendingUp", icon: TrendingUp, category: "FINANCE", tags: ["growth", "increase", "stocks", "profit"] },
  { id: "TrendingDown", icon: TrendingDown, category: "FINANCE", tags: ["loss", "decrease", "stocks", "deficit"] },
  { id: "Percent", icon: Percent, category: "FINANCE", tags: ["discount", "rate", "interest", "tax"] },
  { id: "Calculator", icon: Calculator, category: "FINANCE", tags: ["math", "numbers", "finance", "calculate"] },
  { id: "PieChart", icon: PieChart, category: "FINANCE", tags: ["data", "graph", "analysis", "distribution"] },
  { id: "BarChart", icon: BarChart3, category: "FINANCE", tags: ["data", "graph", "analysis", "growth"] },
  { id: "Gift", icon: Gift, category: "FINANCE", tags: ["present", "celebration", "reward", "surprise"] },
  { id: "Tag", icon: Tag, category: "FINANCE", tags: ["price", "label", "shopping", "discount"] },
  { id: "Ticket", icon: Ticket, category: "FINANCE", tags: ["event", "entry", "pass", "movie"] },
  { id: "Bitcoin", icon: Bitcoin, category: "FINANCE", tags: ["crypto", "money", "currency", "digital"] },
  { id: "Gem", icon: Gem, category: "FINANCE", tags: ["value", "rich", "diamond", "rare"] },
  { id: "HandCoins", icon: HandCoins, category: "FINANCE", tags: ["give", "pay", "money", "receive"] },
  { id: "ReceiptYen", icon: ReceiptJapaneseYen, category: "FINANCE", tags: ["bill", "jpy", "money", "invoice"] },
  { id: "Scale", icon: Scale, category: "FINANCE", tags: ["balance", "justice", "law", "compare"] },
  { id: "ShieldCheck", icon: ShieldCheck, category: "FINANCE", tags: ["secure", "safe", "verified", "protection"] },
  { id: "ShoppingBasket", icon: ShoppingBasket, category: "FINANCE", tags: ["buy", "grocery", "shop", "items"] },
  { id: "Store", icon: Store, category: "FINANCE", tags: ["business", "shop", "local", "sell"] },
  { id: "Vault", icon: Vault, category: "FINANCE", tags: ["safe", "secure", "money", "bank"] },
  { id: "CircleDollar", icon: CircleDollarSign, category: "FINANCE", tags: ["money", "currency", "cash", "usd"] },
  { id: "Bank", icon: Bank, category: "FINANCE", tags: ["money", "institution", "save", "finance"] },
  { id: "Salary", icon: BriefcaseMoney, category: "FINANCE", tags: ["work", "salary", "business", "pay"] },
  { id: "LineChart", icon: LineChart, category: "FINANCE", tags: ["data", "stocks", "growth", "profit"] },

  // [ HOME & LIFE ]
  { id: "Home", icon: Home, category: "HOME & LIFE", tags: ["house", "building", "stay", "life"] },
  { id: "Building", icon: Building2, category: "HOME & LIFE", tags: ["office", "apartment", "city", "work"] },
  { id: "Car", icon: Car, category: "HOME & LIFE", tags: ["vehicle", "transport", "drive", "travel"] },
  { id: "Plane", icon: Plane, category: "HOME & LIFE", tags: ["travel", "flight", "airport", "vacation"] },
  { id: "Train", icon: TrainFront, category: "HOME & LIFE", tags: ["travel", "rail", "commute", "transport"] },
  { id: "Bus", icon: Bus, category: "HOME & LIFE", tags: ["travel", "commute", "transport", "public"] },
  { id: "Map", icon: Map, category: "HOME & LIFE", tags: ["location", "travel", "navigation", "direction"] },
  { id: "MapPin", icon: MapPin, category: "HOME & LIFE", tags: ["location", "address", "marker", "here"] },
  { id: "Navigation", icon: Navigation, category: "HOME & LIFE", tags: ["gps", "direction", "travel", "pointer"] },
  { id: "Coffee", icon: Coffee, category: "HOME & LIFE", tags: ["drink", "morning", "caffeine", "break"] },
  { id: "Pizza", icon: Pizza, category: "HOME & LIFE", tags: ["food", "meal", "dinner", "unhealthy"] },
  { id: "Beer", icon: Beer, category: "HOME & LIFE", tags: ["drink", "alcohol", "party", "social"] },
  { id: "Wine", icon: Wine, category: "HOME & LIFE", tags: ["drink", "alcohol", "dinner", "party"] },
  { id: "Cake", icon: Cake, category: "HOME & LIFE", tags: ["food", "sweet", "dessert", "birthday"] },
  { id: "Candy", icon: Candy, category: "HOME & LIFE", tags: ["food", "sweet", "sugar", "snack"] },
  { id: "Cookie", icon: Cookie, category: "HOME & LIFE", tags: ["food", "snack", "sweet", "treat"] },
  { id: "Music", icon: Music, category: "HOME & LIFE", tags: ["audio", "sound", "song", "listen"] },
  { id: "Gamepad", icon: Gamepad2, category: "HOME & LIFE", tags: ["games", "play", "controller", "fun"] },
  { id: "Tv", icon: Tv, category: "HOME & LIFE", tags: ["watch", "entertainment", "display", "screen"] },
  { id: "Brush", icon: Brush, category: "HOME & LIFE", tags: ["art", "draw", "paint", "creative"] },
  { id: "Hammer", icon: Hammer, category: "HOME & LIFE", tags: ["tool", "fix", "work", "repair"] },
  { id: "Wrench", icon: Wrench, category: "HOME & LIFE", tags: ["tool", "fix", "repair", "mechanic"] },
  { id: "Shirt", icon: Shirt, category: "HOME & LIFE", tags: ["clothing", "laundry", "wear", "fashion"] },
  { id: "Glasses", icon: Glasses, category: "HOME & LIFE", tags: ["vision", "see", "read", "accessory"] },
  { id: "Sun", icon: Sun, category: "HOME & LIFE", tags: ["weather", "day", "light", "warm"] },
  { id: "Moon", icon: Moon, category: "HOME & LIFE", tags: ["weather", "night", "dark", "sleep"] },
  { id: "CloudRain", icon: CloudRain, category: "HOME & LIFE", tags: ["weather", "water", "wet", "outdoor"] },
  { id: "CloudSnow", icon: CloudSnow, category: "HOME & LIFE", tags: ["weather", "cold", "winter", "outdoor"] },
  { id: "CloudLightning", icon: CloudLightning, category: "HOME & LIFE", tags: ["weather", "storm", "power", "danger"] },
  { id: "Sunrise", icon: Sunrise, category: "HOME & LIFE", tags: ["morning", "day", "start", "sky"] },
  { id: "Sunset", icon: Sunset, category: "HOME & LIFE", tags: ["evening", "night", "end", "sky"] },
  { id: "Armchair", icon: Armchair, category: "HOME & LIFE", tags: ["relax", "furniture", "sit", "home"] },
  { id: "Binoculars", icon: Binoculars, category: "HOME & LIFE", tags: ["look", "see", "vision", "find"] },
  { id: "Bird", icon: Bird, category: "HOME & LIFE", tags: ["animal", "nature", "pet", "sky"] },
  { id: "Bomb", icon: Bomb, category: "HOME & LIFE", tags: ["danger", "boom", "game", "timer"] },
  { id: "BookHeart", icon: BookHeart, category: "HOME & LIFE", tags: ["read", "love", "diary", "romance"] },
  { id: "ChefHat", icon: ChefHat, category: "HOME & LIFE", tags: ["cook", "food", "kitchen", "meal"] },
  { id: "Construction", icon: Construction, category: "HOME & LIFE", tags: ["work", "build", "road", "warning"] },
  { id: "DoorOpen", icon: DoorOpen, category: "HOME & LIFE", tags: ["enter", "home", "exit", "welcome"] },
  { id: "Eraser", icon: Eraser, category: "HOME & LIFE", tags: ["remove", "clean", "delete", "mistake"] },
  { id: "Hotel", icon: Hotel, category: "HOME & LIFE", tags: ["travel", "stay", "sleep", "vacation"] },
  { id: "Luggage", icon: Luggage, category: "HOME & LIFE", tags: ["travel", "bag", "vacation", "trip"] },
  { id: "Microwave", icon: Microwave, category: "HOME & LIFE", tags: ["kitchen", "food", "cook", "hot"] },
  { id: "PartyPopper", icon: PartyPopper, category: "HOME & LIFE", tags: ["celebrate", "birthday", "event", "fun"] },
  { id: "PawPrint", icon: PawPrint, category: "HOME & LIFE", tags: ["animal", "pet", "dog", "cat"] },
  { id: "Refrigerator", icon: Refrigerator, category: "HOME & LIFE", tags: ["kitchen", "food", "cold", "storage"] },
  { id: "Sofa", icon: Sofa, category: "HOME & LIFE", tags: ["relax", "furniture", "sit", "living"] },
  { id: "Tractor", icon: Tractor, category: "HOME & LIFE", tags: ["farm", "work", "vehicle", "nature"] },
  { id: "Waves", icon: Waves, category: "HOME & LIFE", tags: ["water", "ocean", "nature", "relax"] },

  // [ MINDFULNESS ]
  { id: "Sparkles", icon: Sparkles, category: "MINDFULNESS", tags: ["magic", "clean", "spirit", "bright"] },
  { id: "Forest", icon: Forest, category: "MINDFULNESS", tags: ["nature", "forest", "peace", "growth"] },
  { id: "Bloom", icon: Bloom, category: "MINDFULNESS", tags: ["bloom", "peace", "nature", "beauty"] },
  { id: "Organic", icon: Organic, category: "MINDFULNESS", tags: ["nature", "growth", "green", "calm"] },
  { id: "Dream", icon: Dream, category: "MINDFULNESS", tags: ["night", "rest", "dream", "calm"] },
  { id: "Ear", icon: Ear, category: "MINDFULNESS", tags: ["listen", "present", "hear", "aware"] },
  { id: "Grounded", icon: Grounded, category: "MINDFULNESS", tags: ["stable", "hold", "secure", "grounded"] },
  { id: "Guide", icon: Guide, category: "MINDFULNESS", tags: ["guide", "path", "find", "direction"] },
  { id: "Soft", icon: Soft, category: "MINDFULNESS", tags: ["light", "peace", "soft", "nature"] },
  { id: "Endless", icon: Endless, category: "MINDFULNESS", tags: ["peace", "cycle", "limitless", "forever"] },
  { id: "Vibrate", icon: Vibrate, category: "MINDFULNESS", tags: ["energy", "vibration", "motion", "alert"] },
  { id: "CloudSun", icon: CloudSun, category: "MINDFULNESS", tags: ["hope", "light", "nature", "warm"] },
  { id: "Dna", icon: Dna, category: "MINDFULNESS", tags: ["life", "core", "structure", "self"] },
  { id: "Rainbow", icon: Rainbow, category: "MINDFULNESS", tags: ["hope", "color", "happy", "nature"] },
  { id: "MindCircuit", icon: MindCircuit, category: "MINDFULNESS", tags: ["mind", "mental", "smart", "circuit"] },
  { id: "Vitality", icon: Vitality, category: "MINDFULNESS", tags: ["health", "life", "pulse", "vitality"] },
  { id: "VitalEnergy", icon: VitalEnergy, category: "MINDFULNESS", tags: ["energy", "light", "sun", "vitality"] },
  { id: "Peace", icon: Peace, category: "MINDFULNESS", tags: ["peace", "solid", "nature", "climb"] },
  { id: "Flow", icon: Flow, category: "MINDFULNESS", tags: ["water", "flow", "rhythm", "ocean"] },
  { id: "Zen", icon: Zen, category: "MINDFULNESS", tags: ["zen", "yoga", "meditate", "peace"] },
];
